gather_financial_statement_time_series
UBC-MDS/pyntrinio pull request #48
Opened 2020-03-05 21:42 UTC by aakanksha023

- Finished function gather_financial_statement_time_series
- Added exceptions and asserts

2020-03-06 06:10 UTC, sirine-chahma requested changes

2020-03-06 06:10 UTC, sirine-chahma commented on pyntrinio/pyntrinio.py
> +def gather_financial_statement_time_series(api_key, ticker, statement, year, period):
Why did you get rid of the output_format?

2020-03-06 06:10 UTC, sirine-chahma commented on pyntrinio/pyntrinio.py
> +        results.append(my_dict)
I think that would be better if you could also return a list of dictionnaries (the results object), if this is what the user specified in the inputs of the function

2020-03-06 17:32 UTC, aakanksha023 commented
- Addressed feedback
- Added relevant tests

2020-03-07 15:41 UTC, sirine-chahma approved these changes

2020-03-07 15:41 UTC, merged